### ISSUE TITLE
Not possible to use proj from conda env

### ISSUE THREAD

**Issue by zingi** [georust/proj-sys#10]
I would like to use this rust proj bindings, with the proj lib from a conda env. My OS is Pop!_OS 19.10 and the most easy way to install the proj lib is via a conda env:
```bash
conda create --name proj7 -c conda-forge python=3 proj proj-data
```
However, when I try to compile it, I get the same error which is described in this [issue](https://github.com/georust/proj-sys/issues/3): 
```
wrapper.h:1:10: fatal error: 'proj.h' file not found
wrapper.h:1:10: fatal error: 'proj.h' file not found, err: true
thread 'main' panicked at 'Unable to generate bindings: ()', src/libcore/result.rs:1188:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:84
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1025
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:193
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:471
  11: rust_begin_unwind
             at src/libstd/panicking.rs:375
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:84
  13: core::result::unwrap_failed
             at src/libcore/result.rs:1188
  14: core::result::Result<T,E>::expect
             at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/result.rs:983
  15: build_script_build::main
             at ./build.rs:18
  16: std::rt::lang_start::{{closure}}
             at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/rt.rs:67
  17: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  18: std::panicking::try::do_call
             at src/libstd/panicking.rs:292
  19: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  20: std::panicking::try
             at src/libstd/panicking.rs:270
  21: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  22: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  23: std::rt::lang_start
             at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/rt.rs:67
  24: main
  25: __libc_start_main
  26: _start
```
I guess the problem lies here:
https://github.com/georust/proj-sys/blob/779703e3dae58dee3f908f03eb8b47ca07c3c30e/build.rs#L49
which looks to me, like the path is hardcoded.

Would it be possible to manually tell the build script the path to the Proj Lib somehow, for e.g. by an environment variable?

With my proj conda install, the proj lib is located at: `$HOME/anaconda3/envs/proj7`
```
❯ tree $HOME/anaconda3/envs/proj7 -L 1
/home/aaron/anaconda3/envs/proj7
├── bin
├── compiler_compat
├── conda-meta
├── etc
├── include
├── lib
├── sbin
├── share
├── ssl
└── x86_64-conda_cos6-linux-gnu
```

**Comment by urschrei** [comment]
My assumption is that conda installs the proj lib on a non-standard path, or in some way that isn't discoverable by the build script – the line you point to isn't hard-coded as such, it just asks the linker to search the "standard" paths it knows about. I'm working on a fix for #3, but I'm currently a bit time constrained, and it's not clear to me that the fix will apply to this problem anyway. I don't _think_ there's an easy way to pass additional paths to the build script at compile time – I certainly haven't seen anything about it in the documentation. Building proj from source on Linux is [very straightforward](https://github.com/georust/proj-sys/blob/master/.travis.yml#L10), and is probably the easiest way to get going for now…

**Comment by urschrei** [comment]
Hi @zingi, please try the `pkg-config` and / or `bundled_proj` features to see whether this resolves the issue.

**Comment by urschrei** [comment]
Closing as inactive.
